# Generated by Django 5.2.6 on 2025-12-06 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Unique certificate identifier', max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF certificate file', null=True, upload_to='certificates/')),
                ('verification_url', models.URLField(blank=True, help_text='URL to verify certificate authenticity')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin announcement to top')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Announcement',
                'verbose_name_plural': 'Course Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video File'), ('audio', 'Audio File'), ('link', 'External Link'), ('code', 'Code Repository'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload file for this resource', null=True, upload_to='course_resources/')),
                ('external_url', models.URLField(blank=True, help_text="External URL if resource_type is 'link'")),
                ('is_free', models.BooleanField(default=True, help_text='Available to all or only enrolled students')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at', '-helpful_count'], 'verbose_name': 'Course Review', 'verbose_name_plural': 'Course Reviews'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-code')", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show category in listings'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_certificate_available',
            field=models.BooleanField(default=False, help_text='Certificate available upon completion'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese'), ('it', 'Italian')], default='es', help_text='Course language', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times course was viewed'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who found this helpful'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Review from verified enrollment'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-rating'], name='lms_courser_course__4277dd_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['-created_at'], name='lms_courser_created_070f10_idx'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='lms.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='lms.enrollment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='lms.course'),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lms.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for better searchability', related_name='courses', to='lms.tag'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_featured'], name='lms_course_status_e70364_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='lms_course_categor_3c9446_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-published_at'], name='lms_course_publish_4b9889_idx'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_users', to='lms.course'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='lms_certifi_certifi_3bc406_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', '-issued_at'], name='lms_certifi_student_72ce39_idx'),
        ),
        migrations.AddIndex(
            model_name='courseannouncement',
            index=models.Index(fields=['course', '-is_pinned', '-created_at'], name='lms_coursea_course__b1a006_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'course')},
        ),
    ]
